Итерация №5
ex0rcist/metflix pull request #5
Opened 2024-07-06 14:22 UTC by ex0rcist

2024-07-10 07:55 UTC, tmvrus requested changes
есть вопросы

2024-07-10 07:55 UTC, tmvrus commented on cmd/agent/main.go
> +	}
достаточно запустить агент синхронно, то есть не ф-ю  a.startReporting() в горутине

2024-07-10 07:55 UTC, tmvrus commented on cmd/server/main.go
> +		return
что бы записать эту в одну строку можно использовать метод log.Fatal

2024-07-10 07:55 UTC, tmvrus commented on internal/agent/agent.go
> +		fmt.Printf("%+v\n", err)
в проекте уже есть логер, использовать fmt для логирования не стоит

2024-07-10 07:55 UTC, tmvrus commented on internal/agent/agent.go
> +	return nil // return error from goroutine?
а смысл? агент должен работать постоянно

2024-07-10 07:55 UTC, tmvrus commented on internal/agent/agent.go
> +			return // todo: handle errors
логировать например

2024-07-10 07:55 UTC, tmvrus commented on internal/agent/agent_test.go
> +	// HELP: как тестировать приватные?
никак)
только через контракты

2024-07-10 07:55 UTC, tmvrus commented on internal/agent/api.go
> +		panic(err)
тут панику использовать не стоит, посколько можно сделать обработку ошибки
https://go.dev/wiki/CodeReviewComments#dont-panic

2024-07-10 07:55 UTC, tmvrus commented on internal/agent/api.go
> +		panic(err)
тоже самое

2024-07-10 07:55 UTC, tmvrus commented on internal/agent/api.go
> +	}
тут потенциальная проблема, если будет ошибка то respBody будет nil и прочитать оттуда StatusCode не получится, будет паника и программа схлопнется, читать respBody нужно только если ошибки не было

2024-07-10 07:55 UTC, tmvrus commented on internal/agent/stats.go
> +	// todo: errors?
а зачем?
и ошибка непонятно зачем есть в сигнатуре, она ведь никогда не возвращается

2024-07-10 07:55 UTC, tmvrus commented on internal/logging/logging.go
> +	// zerolog.ErrorStackMarshaler = pkgerrors.MarshalStack
не понимаю о чем это, если нужно разобраться приходи на 1-1

2024-07-10 07:55 UTC, tmvrus commented on internal/server/handlers.go
> +		panic("unable to write") // todo
ошибка в одном запросе уронит все приложение, именно так тут сработает паника
по этому не стоит ей пользоваться

2024-07-10 07:55 UTC, tmvrus commented on internal/server/handlers.go
> +		}
получается, если ошибка. то просто продолжим работать?

2024-07-10 07:55 UTC, tmvrus commented on internal/server/handlers.go
> +	}
паника уронит все приложение, от одного кривого запроса

2024-07-10 07:55 UTC, tmvrus commented on internal/storage/memory.go
> +// Too complicated? mb easy way?
нет, это так работает в статических языках

2024-07-10 10:52 UTC, ex0rcist commented on cmd/agent/main.go
> +	}
Проблема была в том, что программа завершалась до того, как начнутся циклы в горутинах. Все же разобрался как запустить горутины через sync.WaitGroup. Их там две, потому что все же это два отдельных "процесса", по опросу стат и их отправке. Если их запустить в одном цикле то непонятно как разделить их интервалы запуска. Поэтому сделал через горутины.

2024-07-11 14:59 UTC, tmvrus commented on cmd/agent/main.go
> +	}
достаточно было запустить одну в горутине, второе синхронно
но то что ты самостоятельно добрался до WaitGroup это просто отлично

2024-07-11 14:59 UTC, tmvrus approved these changes

2024-07-11 15:06 UTC, merged