Инкремент №9
ex0rcist/metflix pull request #9
Opened 2024-07-25 12:04 UTC by ex0rcist

2024-07-26 11:22 UTC, tmvrus requested changes
есть вопросы

2024-07-26 11:22 UTC, tmvrus commented on internal/agent/api.go
> +	var mex metrics.MetricExchange
из этих 3 строк, var нужен только в последней, просто правило как выбрать между := и var
- если переменная инициализируется как zero-value то рекомендуется использовать var
- во всех остальных случаях разумно использовать :=

2024-07-26 11:22 UTC, tmvrus commented on internal/agent/api.go
> +	// использовать рефлексию через metric.(type) ?
можно но не стоит)
рефлексия оч специфический инструмент, если есть набор конечных состояний то лучше ее избежать

2024-07-26 11:22 UTC, tmvrus commented on internal/agent/api.go
> +	case "gauge":
строки "counter" и "gauge" встречаются повсеместно в проекте, есть смысл сделать их константами и переиспользовать

2024-07-26 11:22 UTC, tmvrus commented on internal/agent/api.go
> +	// использовать рефлексию через metric.(type) ?
тут вполне можно обойтись type switch

2024-07-26 11:22 UTC, tmvrus commented on internal/compression/decompressor.go
> +	if _, ok := d.supportedEncodings[encoding]; !ok {
не самый надежный способ, потому что в заголовке может быть несколько значений
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding#compressing_with_gzip

2024-07-26 11:22 UTC, tmvrus commented on internal/metrics/types.go
> +
?

2024-07-26 11:22 UTC, tmvrus commented on internal/middleware/middleware.go
> +			Str("remote-addr", r.RemoteAddr). // middleware.RealIP
На всякий случай предупрежу, в реальной системе тут врядли будет адрес автора запроса. Потому что в реальных системах запросы идут через один или несколько прокси, например nginx или haproxy. Чаще всего настроящий IP-адресс клиента будет в заголовке X-Forwarded-For
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

2024-07-26 11:22 UTC, tmvrus commented on internal/server/handlers.go
>  	// http.Error(w, resp, code)
не стоит оставлять закоменченый код в проекте, это дурной тон, засоряет проект и усложняет чтение

2024-07-26 11:22 UTC, tmvrus commented on internal/server/server.go
> +}
Server вообще ничего не должен знать про загрузку с диска, разумнее всего это делать при создании экземпляра хранилища, передавая ему конфигурацию. Такая реализация это пример "abstraction leak" когда особенности хранения "протекают" на другие слои.

2024-07-26 11:22 UTC, tmvrus commented on internal/server/server.go
> +		}
все тоже самое, сохраннеие можно было реализовать внутри сторадажа, и ничего не говорить об этом серверу

2024-07-26 11:22 UTC, tmvrus commented on internal/storage/storage.go
> +	Kind() string
само по себе наличие этого метода нарушает принцип инкапсуляции, рассказывать вызывающему коду о внутреннем устройстве это лишнее. Боле того, добавлять в специальные состояние/флаги которые говорят о том, что это "тест" (mock) это повод задуматься редизайне приложения.

2024-07-26 14:37 UTC, ex0rcist commented on internal/compression/decompressor.go
> +	if _, ok := d.supportedEncodings[encoding]; !ok {
@tmvrus не очень понял тут. Это декомпрессия входящего запроса, мы проверяем Content-Encoding, там либо одна кодировка, либо несколько, в последовательном порядке их применения. Т.к. мы умеем распаковывать только gzip, то и проверяем только его.

Если речь про Accept-Encoding, то там проверяю все заголовки - https://github.com/ex0rcist/metflix/pull/9/files/42a295da31674147c0c10eb19ec8b95e85e8a52a#diff-3413224df30ede06962678504193d621a87171fd26eed154919225315109efd7R111

2024-07-26 14:42 UTC, ex0rcist commented on internal/middleware/middleware.go
> +			Str("remote-addr", r.RemoteAddr). // middleware.RealIP
Спасибо, последнее время у нас этим занимались системные администраторы, и мы в конфигурациях использовали x-real-ip (от nginx), потому что знали что ему можно доверять. Тема стоит отдельного изучения

2024-07-26 14:45 UTC, ex0rcist commented on internal/server/server.go
> +}
Вообще я так и сделал изначально, но мне не понравилось что после создания Storage начинает сам себя дампать на диск, пока сервер еще формально не запущен ( Run())

Я перенес обратно в storage как было, а в сервере возможно стоит сделать CreateAndRun() вместо New() и Run() ? Или не стоит заморачиваться вообще

2024-07-28 19:44 UTC, tmvrus commented on internal/compression/decompressor.go
> +	if _, ok := d.supportedEncodings[encoding]; !ok {
Если там будет `Content-Encoding: deflate, gzip` код отработает?

2024-07-28 19:44 UTC, tmvrus commented on internal/server/server.go
> +}
ТАк а зачем серверу вообще знать про какой-то Run, есть для сервера в этом хоть какой-то смысл? Если нет, то и знать незачем.

2024-07-29 06:29 UTC, ex0rcist commented on internal/compression/decompressor.go
> +	if _, ok := d.supportedEncodings[encoding]; !ok {
Нет, а должен? Гугл говорит что `Content-Encoding: deflate` это данные в формате zlib, тогда как `Content-Encoding: gzip` это данные в формате gzip, и обе этих либы используют алгоритм сжатия deflate. Но для распаковки zlib надо использовать другую библиотеку, т.к.заголовки у сжатых данных отличаются

2024-07-29 12:53 UTC, tmvrus approved these changes
Хорошая работа

2024-07-29 19:38 UTC, merged